### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by EyupErgin** [TurkOsint/WebScrapper#2]
[TurkOsint] Taranacak Kelimeleri Giriniz > Bill Gates
[TurkOsint] Taranıyor > Bill Gates
Traceback (most recent call last):
  File "WebScrapper.py", line 29, in <module>
    for url in search(query, stop = results):
  File "/home/bughunter/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 305, in search
    html = get_page(url, user_agent, verify_ssl)
  File "/home/bughunter/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 174, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

Hata Kodu : 429. Çok fazla request atıldığında bu hata alınıyor. Bug ve Enhancement olarak işaretlendi.

**Comment by EyupErgin** [comment]
Kodlarda Result Değerini Düşürüp, User Agent ve Proxy Eklemesini Bir sonraki V2.0 Sürümünde Yayımlanacak. Böylece IP Google tarafında blacklist'e düşmeyecek. 

Sorunu,
Result, UserAgent ve Proxy çözümleriyle bitireceğiz.

**Comment by EyupErgin** [comment]
Sorun Tamamıyla Çözülmüştür.
